### ISSUE TITLE
FYI: csvy format

### ISSUE THREAD

**Issue by billdenney** [bergsmat/yamlet#4]
Hi @bergsmat ,

I just learned of this package, and I thought that you might want to know of the csvy package as it has partially overlapping goals: https://github.com/leeper/csvy

**Comment by bergsmat** [comment]
@billdenney: Hi Bill!

Thanks for the heads up.  Yes, I’ve come across csvy before.  Interestingly, both packages support having metadata in a companion file, while only csvy supports having everything in one file.  I like the all-in-one approach because it makes it much more likely that the metadata won’t get separated from the data.  On the other hand, if you keep them separate, there are more tools that read either.  Thanks for feedback, and feel free to discuss further.

**Comment by billdenney** [comment]
I just learned of the package, and my first look found it very interesting.  (I'm specifically interesting in combining yamlet with table1.)  I didn't have anything deeper to contribute than "csvy exists" at the moment in case it would help with some of the tooling or rest of the ecosystem.  I'm sure you'll be hearing more from me as I explore further.
